### ISSUE TITLE
gino.exceptions.UninitializedError: Gino engine is not initialized.

### ISSUE THREAD

**Issue by arnaudsj** [leosussan/fastapi-gino-arq-uvicorn#1]
Hi,

I am interested in getting this exact same stack up and running, but after I clone, install all the dependencies and setup the DATABASE in the .env file and run python app/main.py and I get the following error:
```
$ python app/main.py 
INFO: Uvicorn running on http://localhost:8888 (Press CTRL+C to quit)
INFO: Started reloader process [49720]
INFO: Started server process [49722]
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: ('127.0.0.1', 59591) - "GET / HTTP/1.1" 500
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 370, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 81, in __call__
    raise exc from None
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/uvicorn/middleware/debug.py", line 78, in __call__
    await self.app(scope, receive, inner_send)
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/starlette/applications.py", line 133, in __call__
    await self.error_middleware(scope, receive, send)
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/starlette/middleware/errors.py", line 122, in __call__
    raise exc from None
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/starlette/middleware/errors.py", line 100, in __call__
    await self.app(scope, receive, _send)
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/gino/ext/starlette.py", line 73, in __call__
    scope['connection'] = await self.db.acquire(lazy=True)
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/gino/api.py", line 481, in acquire
    return self.bind.acquire(*args, **kwargs)
  File "/Users/arnaudsj/.local/share/virtualenvs/h7IURhCI/lib/python3.7/site-packages/gino/api.py", line 501, in __getattribute__
    raise self._exception
gino.exceptions.UninitializedError: Gino engine is not initialized.
```

**Comment by leosussan** [comment]
Apologies for the delay in response.

The `UnunitializedError` typically pops up when Gino attempts to connect to the database and fails, which would indicate a settings mismatch.

What does your .env's `DATABASE` variable read as? What are the preferences set by other applications that use your local postgres instance?

**Comment by leosussan** [comment]
Following up on this - were you able to get things running?

**Comment by leosussan** [comment]
Going to close this, assuming things have been resolved.
